name: Continuous Integration

on: [pull_request, workflow_dispatch]

env:
  FLUTTER_VERSION: "3.19.5"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/setup-and-cache.yml
        with:
          java-version: 12.x
          flutter-version: ${{ env.FLUTTER_VERSION }}

  analyze:
    timeout-minutes: 15
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Configure Java, Cache, and Prepare Environment
        uses: ./.github/workflows/setup-and-cache.yml
        with:
          java-version: 12.x
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Dart Analyze
        run: melos run analyze

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: setup
    steps:
      - name: Configure Java, Cache, and Prepare Environment
        uses: ./.github/workflows/setup-and-cache.yml
        with:
          java-version: 12.x
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Formatter
        run: melos run format

      - name: Validate Formatting
        run: ./.github/workflows/scripts/validate-formatting.sh

  build_torch_controller_example_ubuntu:
    timeout-minutes: 20
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Configure Java, Cache, and Prepare Environment
        uses: ./.github/workflows/setup-and-cache.yml
        with:
          java-version: 12.x
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build torch_controller_example app bundle
        run: cd packages/torch_controller/example && flutter build appbundle

  test_torch_controller:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: setup
    steps:
      - name: Configure Java, Cache, and Prepare Environment
        uses: ./.github/workflows/setup-and-cache.yml
        with:
          java-version: 12.x
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Flutter Test
        run: melos run test:torch:controller

  test_storage_controller:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: setup
    steps:
      - name: Configure Java, Cache, and Prepare Environment
        uses: ./.github/workflows/setup-and-cache.yml
        with:
          java-version: 12.x
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Flutter Test
        run: melos run test:storage:controller
